# Generated by Django 4.2.13 on 2024-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender_type',
            field=models.CharField(choices=[('1', 'Men'), ('2', 'Women'), ('3', 'kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('sm', 'SM'), ('md', 'MD'), ('lg', 'LG'), ('xl', 'XL'), ('2xl', '2XL')], max_length=10),
        ),
    ]
